In [ ]:
#Read the file 

In [18]:
with open('Data/train_corpus.txt', 'r') as f:

    text = f.read()

In [19]:
text

"--- Start of /Users/meskara/Downloads/Supplementary file/Amine_Meskar_Resume__Copy_ (1).pdf ---\nAMINE MESKAR\nWarsaw, Poland |(+48) 782-785-537 |Meskaramine2@gmail.com |LinkedIn |Portfolio\nRÉSUMÉ\nData scientist à l’interface industrie–recherche . Chez OCP , et un centre nucléaire en Pologne, j’ai mis en production\ndes modèles d’optimisation et de maintenance prédictive, générant plus de 2M$ de valeur cumulée. Je mets\naujourd’hui cette expertise internationale au service de projets d’IA appliquée , en combinant impact métier,\nperspective scientifique, et autonomie d’exécution.\nCOMPÉTENCES\n•Langages :Python (TensorFlow, PyTorch), C++, R, SQL\n•Modélisation : classification, régression, séries temporelles, NLP , LLM , clustering, détection d’anomalies, explainable AI\n•Cloud&MLOps :AWS (SageMaker, S3) , PySpark, Databricks, CI/CD, pipelines distribués\n•Langues : Arabe (natif), Français (professionnel), Anglais (courant)\nEXPÉRIENCES\nData Scientist Oct 2024 – Present\nCentre Nat

In [ ]:
#process the text , rmove url and some charcters

In [ ]:
import re

def preprocess_text(text):
    
    if not isinstance(text, str):
        return ""

    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    text = re.sub(r"/[^\s]+", "", text)

    text = re.sub(r'\n', '', text)

    return text.strip()

In [21]:
text = preprocess_text(text)

In [22]:
text

"--- Start of  file (1).pdf ---AMINE MESKARWarsaw, Poland |(+48) 782-785-537 |Meskaramine2@gmail.com |LinkedIn |PortfolioRÉSUMÉData scientist à l’interface industrie–recherche . Chez OCP , et un centre nucléaire en Pologne, j’ai mis en productiondes modèles d’optimisation et de maintenance prédictive, générant plus de 2M$ de valeur cumulée. Je metsaujourd’hui cette expertise internationale au service de projets d’IA appliquée , en combinant impact métier,perspective scientifique, et autonomie d’exécution.COMPÉTENCES•Langages :Python (TensorFlow, PyTorch), C++, R, SQL•Modélisation : classification, régression, séries temporelles, NLP , LLM , clustering, détection d’anomalies, explainable AI•Cloud&MLOps :AWS (SageMaker, S3) , PySpark, Databricks, CI pipelines distribués•Langues : Arabe (natif), Français (professionnel), Anglais (courant)EXPÉRIENCESData Scientist Oct 2024 – PresentCentre National de Recherche Nucléaire Varsovie, Pologne•Déploiement de GNN pour la détection de signaux crit

In [23]:
print('Lenght of my text', len(text))

Lenght of my text 120780


In [24]:
chars = sorted(list(set(text)))

vocab = len(chars)

print(''.join(chars))
print(vocab)

 $%&'()+,-./0123456789:;=@ABCDEFGHIJKLMNOPQRSTUVWXY[]`abcdefghijklmnopqrstuvwxyz|´µ¶¸Éàâçèéêîïóôùûıœˆν–—’“”•→♂
110


In [ ]:
# Tokeization in the character level

In [39]:
ztoa = {i:k for i,k in enumerate(chars)}
atoz = {k:i for i,k in enumerate(chars)}

encoding = lambda word: [atoz[w] for w in word]
decoding = lambda word: "".join([ztoa[w] for w in word])

print(encoding('holla 123 hye'))
print(decoding(encoding('holla 123 hye')))

[61, 68, 65, 65, 54, 0, 13, 14, 15, 0, 61, 78, 58]
holla 123 hye


In [47]:
import torch

encoding_text = torch.tensor(encoding(text), dtype= torch.long)

print(encoding_text.shape, encoding_text.dtype)
print(encoding_text[: 1000])

torch.Size([120780]) torch.int64
tensor([  9,   9,   9,   0,  44,  73,  54,  71,  73,   0,  68,  59,   0,   0,
         59,  62,  65,  58,   0,   5,  13,   6,  10,  69,  57,  59,   0,   9,
          9,   9,  26,  38,  34,  39,  30,   0,  38,  30,  44,  36,  26,  43,
         48,  54,  71,  72,  54,  76,   8,   0,  41,  68,  65,  54,  67,  57,
          0,  80,   5,   7,  16,  20,   6,   0,  19,  20,  14,   9,  19,  20,
         17,   9,  17,  15,  19,   0,  80,  38,  58,  72,  64,  54,  71,  54,
         66,  62,  67,  58,  14,  25,  60,  66,  54,  62,  65,  10,  56,  68,
         66,   0,  80,  37,  62,  67,  64,  58,  57,  34,  67,   0,  80,  41,
         68,  71,  73,  59,  68,  65,  62,  68,  43,  85,  44,  46,  38,  85,
         29,  54,  73,  54,   0,  72,  56,  62,  58,  67,  73,  62,  72,  73,
          0,  86,   0,  65, 104,  62,  67,  73,  58,  71,  59,  54,  56,  58,
          0,  62,  67,  57,  74,  72,  73,  71,  62,  58, 102,  71,  58,  56,
         61,  58,  71,  56,  61

In [ ]:
#split train validation

In [53]:
n = int(0.9*len(encoding_text))

train_data = encoding_text[:n]
valid_data = encoding_text[n:]

In [ ]:
# Training with all the data at once is costly, but we can train it with chuncks

In [66]:
train_data[: 8]

tensor([ 9,  9,  9,  0, 44, 73, 54, 71])

In [67]:
train_data[1: 9]

tensor([ 9,  9,  0, 44, 73, 54, 71, 73])

In [70]:
block_size = 8

x = train_data[: block_size]

y = train_data[1: block_size + 1]

for i in range(len(train_data[: block_size])):

    o = x[:i+1]
    j = y[i]

    print(f'whne input is {o} target is {j}')

whne input is tensor([9]) target is 9
whne input is tensor([9, 9]) target is 9
whne input is tensor([9, 9, 9]) target is 0
whne input is tensor([9, 9, 9, 0]) target is 44
whne input is tensor([ 9,  9,  9,  0, 44]) target is 73
whne input is tensor([ 9,  9,  9,  0, 44, 73]) target is 54
whne input is tensor([ 9,  9,  9,  0, 44, 73, 54]) target is 71
whne input is tensor([ 9,  9,  9,  0, 44, 73, 54, 71]) target is 73


In [79]:
# Random sampling

In [99]:
batch_size = 4

def random_sampling(split):

    data = train_data if split == 'train' else valid_data

    ix = torch.randint(len(data) - block_size, (batch_size,))

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x, y

x, y = random_sampling('train')

In [100]:
x[0][:2]

tensor([73,  0])

In [107]:
x

tensor([[ 73,   0,  57, 104,  54,  74,  60,  66],
        [ 67,  60,  54,  60,  58,   0,  67,  54],
        [ 78,  44,  69,  54,  71,  64,  10,  45],
        [ 56,  62,  58,  67,  56,  58,  10,  44]])

In [108]:
y

tensor([[  0,  57, 104,  54,  74,  60,  66,  58],
        [ 60,  54,  60,  58,   0,  67,  54,  73],
        [ 44,  69,  54,  71,  64,  10,  45,  58],
        [ 62,  58,  67,  56,  58,  10,  44,  36]])

In [106]:
for i in range(4):

    for j in range(8):

        x_l = x[i][:j+1]
        y_l = y[i][j]

        print(f"when input is {x_l} the target is {y_l}")



when input is tensor([73]) the target is 0
when input is tensor([73,  0]) the target is 57
when input is tensor([73,  0, 57]) the target is 104
when input is tensor([ 73,   0,  57, 104]) the target is 54
when input is tensor([ 73,   0,  57, 104,  54]) the target is 74
when input is tensor([ 73,   0,  57, 104,  54,  74]) the target is 60
when input is tensor([ 73,   0,  57, 104,  54,  74,  60]) the target is 66
when input is tensor([ 73,   0,  57, 104,  54,  74,  60,  66]) the target is 58
when input is tensor([67]) the target is 60
when input is tensor([67, 60]) the target is 54
when input is tensor([67, 60, 54]) the target is 60
when input is tensor([67, 60, 54, 60]) the target is 58
when input is tensor([67, 60, 54, 60, 58]) the target is 0
when input is tensor([67, 60, 54, 60, 58,  0]) the target is 67
when input is tensor([67, 60, 54, 60, 58,  0, 67]) the target is 54
when input is tensor([67, 60, 54, 60, 58,  0, 67, 54]) the target is 73
when input is tensor([78]) the target is 44